version: '3'
services:
  symfony_site_web:
    container_name: symfony_site_web
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - .:/app
    depends_on:
      - symfony_site_database
    networks:
      - symfony-site
  symfony_site_nginx:
    container_name: symfony_site_nginx
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - symfony_site_web
    networks:
      - symfony-site
  symfony_site_database:
    container_name: symfony_site_database
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/database/schema.sql:/docker-entrypoint-initdb.d/1.sql
      - db_data:/var/lib/mysql
    ports:
      - "3001:3306"
    security_opt:
      - seccomp:unconfined
    networks:
      - symfony-site

volumes:
  db_data:

networks:
  symfony-site:
    driver: bridge